### ISSUE TITLE
Invalid name

### ISSUE THREAD

**Issue by tomtom340** [ebaauw/homebridge-ups#10]
I get the following error in the homebridge log after configuring the plugin:

[12/12/2022, 20:32:29] [UPS] 192.168.0.2: error: RangeError: : invalid name
    at UpsAccessory.set name [as name] (/var/lib/homebridge/node_modules/homebridge-ups/node_modules/homebridge-lib/lib/Delegate.js:108:13)
    at new Delegate (/var/lib/homebridge/node_modules/homebridge-ups/node_modules/homebridge-lib/lib/Delegate.js:38:15)
    at new AccessoryDelegate (/var/lib/homebridge/node_modules/homebridge-ups/node_modules/homebridge-lib/lib/AccessoryDelegate.js:42:5)
    at new UpsAccessory (/var/lib/homebridge/node_modules/homebridge-ups/lib/UpsAccessory.js:68:5)
    at UpsHost.init (/var/lib/homebridge/node_modules/homebridge-ups/lib/UpsHost.js:67:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at UpsPlatform.init (/var/lib/homebridge/node_modules/homebridge-ups/lib/UpsPlatform.js:104:7)

Using the ups -H command in the terminal connects and displays info of my UPS fine. I have a CyberPower CP900EPFCLCD UPS connected to a TrueNAS system.

**Comment by ebaauw** [comment]
What's your config.json?
