### ISSUE TITLE
Homebridge 2.0 Warnings

### ISSUE THREAD

**Issue by awlynn68** [ebaauw/homebridge-ups#23]
I recently updated my Homebridge to 2.0-beta.  The UPS plugin works, but is constantly throwing the following errors.  The listeners number continues to grow with each warning iteration.

8/12/2024, 11:20:57 PM] [UPS] Homebridge: warning: recommended version: API v1.2
[8/12/2024, 11:20:57 PM] [UPS] Homebridge: QBFMX7004179: CPS LX1500GU3 120V UPS with 24V PbAcid battery from CPS
[8/12/2024, 11:20:57 PM] [UPS] On Battery: Configured Name: warning: 2827 listeners
[8/12/2024, 11:20:57 PM] [UPS] On Battery: Mute: warning: 2827 listeners
[8/12/2024, 11:20:57 PM] [UPS] On Battery: Log Level: warning: 2827 listeners
[8/12/2024, 11:20:57 PM] [UPS] Homebridge: warning: TypeError: params.Service: not a Service
    at new ServiceDelegate (file:///var/lib/homebridge/node_modules/homebridge-ups/node_modules/homebridge-lib/lib/ServiceDelegate.js:64:13)
    at new Battery (file:///var/lib/homebridge/node_modules/homebridge-ups/node_modules/homebridge-lib/lib/ServiceDelegate/Battery.js:55:5)
    at new Battery (file:///var/lib/homebridge/node_modules/homebridge-ups/lib/UpsService.js:138:5)
    at new UpsAccessory (file:///var/lib/homebridge/node_modules/homebridge-ups/lib/UpsAccessory.js:92:27)
    at UpsHost.init (file:///var/lib/homebridge/node_modules/homebridge-ups/lib/UpsHost.js:74:37)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UpsPlatform.init (file:///var/lib/homebridge/node_modules/homebridge-ups/lib/UpsPlatform.js:108:7)

The Homebridge plugin JSPN is:
{
    "name": "UPS",
    "hosts": [
        {
            "host": "localhost:3493",
            "username": "local_mon",
            "password": "==================="
        }
    ],
    "platform": "UPS",
    "_bridge": {
        "username": "0E:C4:7A:EA:7C:54",
        "port": 53120
    }
}

The relevant section of ups.conf is:
[cyberpower]
    driver = usbhid-ups
    port = auto
    vendorid = 0764
    pollfreq = 30

**Comment by ebaauw** [comment]
HAP-NodeJS v1 has removed `BatteryService` in favour of `Battery`.

**Comment by ebaauw** [comment]
Could you please try beta v1.2.12-0?

**Comment by awlynn68** [comment]
That fixed the vast majority of the warnings. 

Where is the name of the accessory held?  I renamed the machine and the network name to eliminate the "-" but these accessories are picking it up from somewhere, even after removing them from the cached accessories list.

<img width="803" alt="Screenshot 2024-08-13 at 17 57 01" src="https://github.com/user-attachments/assets/b8078595-f9f9-49d6-8604-2c2d1a368784">

**Comment by ebaauw** [comment]
> That fixed the vast majority of the warnings.

Do you still have any Homebridge UPS related issues?

> Where is the name of the accessory held?

In HomeKit.  On initial pairing, the name is copied from the accessory (i.c. the Homebridge plugin), but afterwards it lives a life of its own.  You can change it in any decent HomeKit app.  Same for service names, except that these are now synced with the _Configured Name_ characteristic, which is accessible to the accessory.

**Comment by awlynn68** [comment]
I fixed the issue. For some reason remove just the cached UPS did not clear the cached accessory completely.  Once I deleted all cached accessories to reverted to the proper name.

I would consider this closed.

**Comment by ebaauw** [comment]
Will issue a proper release after some more Homebridge v2 / HAP-NodeJS v1 testing.
